name: Moodle Plugin CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:${{ matrix.pgversion || '13' }}
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.3'
            moodle-branch: 'MOODLE_500_STABLE'
            database: 'mariadb'
          - php: '8.3'
            moodle-branch: 'MOODLE_500_STABLE'
            database: 'pgsql'
            pgversion: '14'
          - php: '8.2'
            moodle-branch: 'MOODLE_500_STABLE'
            database: 'mariadb'
          - php: '8.2'
            moodle-branch: 'MOODLE_500_STABLE'
            database: 'pgsql'
          - php: '8.2'
            moodle-branch: 'MOODLE_405_STABLE'
            database: 'mariadb'
          - php: '8.2'
            moodle-branch: 'MOODLE_405_STABLE'
            database: 'pgsql'
          - php: '8.2'
            moodle-branch: 'MOODLE_404_STABLE'
            database: 'mariadb'
          - php: '8.2'
            moodle-branch: 'MOODLE_404_STABLE'
            database: 'pgsql'
          - php: '8.1'
            moodle-branch: 'MOODLE_403_STABLE'
            database: 'mariadb'
          - php: '8.1'
            moodle-branch: 'MOODLE_403_STABLE'
            database: 'pgsql'
          - php: '8.1'
            moodle-branch: 'MOODLE_402_STABLE'
            database: 'mariadb'
          - php: '8.1'
            moodle-branch: 'MOODLE_402_STABLE'
            database: 'pgsql'
          - php: '8.0'
            moodle-branch: 'MOODLE_401_STABLE'
            database: 'mariadb'
          - php: '8.0'
            moodle-branch: 'MOODLE_401_STABLE'
            database: 'pgsql'

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          ini-values: max_input_vars=5000

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$(cd ci/bin && pwd)" >> $GITHUB_PATH
          echo "$(cd ci/vendor/bin && pwd)" >> $GITHUB_PATH

      - name: Install Moodle with plugin
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: Lint PHP
        run: moodle-plugin-ci phplint

      - name: PHP Mess Detector
        continue-on-error: true
        run: moodle-plugin-ci phpmd

      - name: Debug – Hinweis zur Plugin-Konfiguration
        run: echo "Nutze aktuell custom phpcs.xml im Plugin-Verzeichnis"

      - name: Code Style
        run: cd plugin && moodle-plugin-ci phpcs --max-warnings=0 --standard=phpcs.xml

      - name: PHPDoc Checker
        continue-on-error: true  # Verhindert Abbruch bei Fehlern
        run: moodle-plugin-ci phpdoc --max-warnings=0

      - name: Validate plugin
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        continue-on-error: true
        run: moodle-plugin-ci mustache

      - name: Grunt
        run: moodle-plugin-ci grunt --max-lint-warnings=0

      - name: Run PHPUnit
        run: moodle-plugin-ci phpunit --fail-on-warning

      - name: Run Behat
        run: moodle-plugin-ci behat --profile chrome